sudo: false
language: ruby
rvm:
- 2.2
branches:
  only:
  - blog-jekyll
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external
after_success:
- git clone https://$GH_REF
- cd $(basename ${GH_REF%.git})
- git config user.name "Travis-CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push -f "https://${DEPLOY_KEY}@${GH_REF}" ${TARGET_BRANCH} > /dev/null 2>&1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/piensa/piensa.github.io.git
  - TARGET_BRANCH: master
  - secure: md6R5N11Gaug/TQBS0tiY2oFDR8Cn3LeC9RIyy+WWGgQod/lFlA1M1GQrTnTw/M3Vpe93YjYVKurO3aSYwt0tpF5WvOb78AieI9gWv5tsozhuKvM+X/Ryeh21134axraTpGufOZhRlP4+3Qcyd+EgEsBPNEn41bIPuF9pA3AuCm9ns69pRESe1b0LKFiBPcFokQYTJ8CeD234lfDmcZ1KoOhfk/FlOt2paxeVE3wr0LJvyzaYo+e/cm5kkWQaYpOzmAqzryvIOOiQaMRpv0J4+RZaVEmaRsY2Pgbxr9OgEr8xBZbhHu6MPJlUII5RVh2LPBvEGcBoAdCQmGWskm171GhBJl/RXyNqIx6RDPjtAT2NWsrjBmyZ5RooU9H0mfvZNb7QBLJyCcH/reV1ZOl6cDUlMzlPRok84gXE146sOjEyvc4DnxpQfjBP8h35aCDheW2fw2IfO/7gZZUE5dSMbmaLYph+m6zPwDy/rfsaBdqTatlTqLl+fj/v48MoEbCBdNx+XyAQ5a0HeQi2mWFjmDktSoYCxRh8g0DgmR6g95CJ7rp5g+14twmqRIgwvvm0FdWLEr318p5IgzICaqwwom2oIYv67vwyq1rCXZNFuFVpPkOUhBMjwh3Gpw+t4kif0e3L3AqnBZAqb2vEHXE3oQr+7s4RyAKPUHsokCyvF4=
  - secure: kQcnlX4yOuKcTVPvwOMPBdMWAh7tzPB9HJviRdXEQ9mF3KyeCwFFglM7eWeRyZoQBdaneTNX6u3kJbQBLDve3ZuOfImHyS5sjg4Ij1DFumqGolasdtLVxBw7iReEBpsunZfxEjJ6ESjO6Q/CLzYd1/wV+o5H6yswIjZduxARHuSa7mXmUcUxjc/HEvqPqVhhe3HUhI+y5mFlcpQfWEmZZQ2jbGRq78WP32UOZke3DeqPJbzNp+w2FgRfZ/ONt8pq6HdzCOr+br1s8dVqwwbiV/5ntyJj7ZZNW3kgMOLKwwOdnWdcal6Ud/Ilt4oZdDUjl9osMX0eGgbEnbyTE3lZaM9sYMNaWc4EAJz6m0C8UBE1WIGAaeyWBy8lhKMhjCoKjgq5PCLE1SuMFAgTnuszg+xhMXPgPXZ7CtPM0DQl0TgPu+R7KXOsNfBWVGnggs+3txyBdYS7w+5KAHE0oIKEaeu8QQ7YacCqt13WcdWQ0oHSomIgIhl/VEXJq5uGm/UlG8QHOuGf7tlYjFyjLNxsHl0cu71hwetgIHP5ZmfBbF8qS+Ed+tQycyC2yVFBr/ye8o5oUGiTicOnwFUyf4yCgtU59k8DOqCcxmghGs74x2uPHUF9YrjV8tlwu4y5lg+bSn3NRkJeDw8W28eXLdKvP3hA3302ajjk/wn9Npx0dcI=
