# Site settings
title: Piensa Labs
email: hello@piensa.co
description: We are Piensa, we become part of your team to tackle difficult challenges through the use of solid engineering, strong communication and usable design.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://piensa.co" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000/" #for developing purposes
paginate: 9
paginate_path: "/blog/page:num/"

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: blog/:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Javier Daza
      layout: "post"
      #comments: true

# Where are categories displayed
include: ["_pages"]

authors:
  javier:
    display_name: Javier Daza
    image_name: javier.jpg
    email: javier@piensa.co
    github: javierdaza
    url: javier-daza

  ariel:
    display_name: Ariel Núñez
    image_name: ariel.jpg
    email: ariel@piensa.co
    github: ingenieroariel
    url: ariel-nunez

  guillermo:
    display_name: Guillermo Solano
    image_name: guillo.jpg
    email: guillermo@piensa.co
    github: gsolat
    url: guillermo-solano