# Site settings
title: Piensa Labs
email: hello@piensa.co
description: We are Piensa, we become part of your team to tackle difficult challenges through the use of solid engineering, strong communication and usable design.
#baseurl: ""
url: "http://piensa.co"
# url: "http://127.0.0.1:4000"
paginate: 9
paginate_path: "/blog/page:num/"

# Gems
gems: [jekyll-paginate]

exclude: [Dockerfile, Gemfile, Gemfile.lock, LICENSE.md, docker-compose.yml, vendor]

# Build settings
markdown: kramdown
highlighter: rouge
permalink: blog/:title

#Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Javier Daza
      layout: "post"
      #comments: true

# Where are categories and authors displayed
include: ["_pages", "_authors"]


authors:
  ariel:
    name: ariel
    display_name: Ariel Núñez
    image_name: ariel.jpg
    email: ariel@piensa.co
    github: ingenieroariel
    description: "Electronic Engineer, specialist in open source software. He is one of the main creators and contributors of GeoNode software. Ariel has worked with NGOs such as the UN (WFP), and the World Bank (GFDRR), developing and promoting the use of open source software for risk assessment and prevention. Make it work."

  cristina:
    name: cristina
    display_name: Cristina Ospino
    image_name: cristy.jpg
    email: cristina@piensa.co
    github: ceon302
    description: "Social Communicator, she worked as a producer in a media agency, she worked as a fundraiser to help the least favored children in the Colombian Caribbean, she worked with a company that focused on the creation of software dedicated in the studies of bathymetry and the coastal floor. Her multidisciplinarity experience and her wanting to help led her to Piensa. Make it matter."

  guillermo:
    name: guillermo
    display_name: Guillermo Solano
    image_name: guillo.jpg
    email: guillermo@piensa.co
    github: gsolat
    description: "Graphic Designer with experience using image to create graphic and visual projects with cultural organizations and social development initiatives. Also, he is a web application developer and enthusiast in the use of open source tools for vectorial and photographic edition. Make it useful."

  javier:
    name: javier
    display_name: Javier Daza
    image_name: javier.jpg
    email: javier@piensa.co
    github: javierdaza
    description: "Electronic Engineer with experience developing apps for Python and PHP. He is the creator of communities like Django Barranquilla and Kizuna Club. Engaging community. Make it work."

  jorge:
    name: jorge
    display_name: Jorge Martinez
    image_name: jorge.jpg
    email: jorge@piensa.co
    github: JorgeMartinezG
    description: "Electronic Engineer and master in electronics. An enthusiast for making machines to learn. He has developed algorithms for object tracking using open-source software. Also, he has developed apps for python and php. Make it work."

  gerson:
    name: gerson
    display_name: Gerson Romero
    image_name: gerson.jpg
    email: gerson@piensa.co
    github: gerdt
    description: "Trained in Electrical Engineering and Business Administration, Social and proactive, makes sure all the i’s have dots and all the t’s are crossed and leads by example. Previous work has involved Neuro-linguistic programming and Quality Management Systems. Make it work."

  wayner:
    name: wayner
    display_name: Wayner Barrios
    image_name: wayner.jpg
    email: waybarrios@gmail.com
    github: waybarrios
    description: "Electronic engineer with experience in Machine Learning and Computer Vision. He has been working for King Abdullah University Science and Technology (KAUST) and Tecnologico de Monterrey (ITESM)  focus on deep learning research and autonomous quadcopter flight, respectively. He has also developed apps for python and Android."
